export class Countries {
    static countries: string[] = [
      'Afganistan',
      'Almanya',
      'Amerika Birleşik Devletleri',
      'Andorra',
      'Angola',
      'Antigua ve Barbuda',
      'Arjantin',
      'Arnavutluk',
      'Avustralya',
      'Avusturya',
      'Azerbaycan',
      'Bahamas',
      'Bahreyn',
      'Bangladeş',
      'Barbados',
      'Belarus',
      'Belçika',
      'Belize',
      'Benin',
      'Bhutan',
      'Birleşik Arap Emirlikleri',
      'Bolivya',
      'Bosna-Hersek',
      'Botsvana',
      'Brezilya',
      'Brunei',
      'Bulgaristan',
      'Burkina Faso',
      'Burundi',
      'Butan',
      'Cezayir',
      'Cibuti',
      'Çad',
      'Çekya',
      'Çin',
      'Danimarka',
      'Dominika',
      'Dominik Cumhuriyeti',
      'Doğu Timor',
      'Ekvador',
      'Ekvator Ginesi',
      'El Salvador',
      'Endonezya',
      'Eritre',
      'Ermenistan',
      'Estonya',
      'Etiyopya',
      'Fas',
      'Fiji',
      'Filipinler',
      'Filistin',
      'Finlandiya',
      'Fransa',
      'Gabon',
      'Gambia',
      'Gana',
      'Gine',
      'Gine-Bissau',
      'Grenada',
      'Guatemala',
      'Guyana',
      'Güney Afrika',
      'Güney Kore',
      'Gürcistan',
      'Haiti',
      'Hırvatistan',
      'Hindistan',
      'Hollanda',
      'Honduras',
      'Irak',
      'İngiltere',
      'İran',
      'İrlanda',
      'İspanya',
      'İsrail',
      'İsveç',
      'İsviçre',
      'İtalya',
      'İzlanda',
      'Jamaika',
      'Japonya',
      'Kamboçya',
      'Kamerun',
      'Kanada',
      'Karadağ',
      'Katar',
      'Kazakistan',
      'Kenya',
      'Kırgızistan',
      'Kiribati',
      'Kolombiya',
      'Komorlar',
      'Kongo Cumhuriyeti',
      'Kongo Demokratik Cumhuriyeti',
      'Kosta Rika',
      'Küba',
      'Kuveyt',
      'Kuzey Kore',
      'Kuzey Makedonya',
      'Laos',
      'Lesotho',
      'Letonya',
      'Liberya',
      'Libya',
      'Liechtenstein',
      'Litvanya',
      'Lüksemburg',
      'Macaristan',
      'Madagaskar',
      'Malavi',
      'Maldivler',
      'Malezya',
      'Mali',
      'Malta',
      'Marshall Adaları',
      'Meksika',
      'Mısır',
      'Mikronezya',
      'Moğolistan',
      'Moldova',
      'Monako',
      'Moritanya',
      'Moritus',
      'Mozambik',
      'Myanmar (Burma)',
      'Namibya',
      'Nauru',
      'Nepal',
      'Nijer',
      'Nijerya',
      'Nikaragua',
      'Norveç',
      'Orta Afrika Cumhuriyeti',
      'Özbekistan',
      'Pakistan',
      'Palau',
      'Panama',
      'Papua Yeni Gine',
      'Paraguay',
      'Peru',
      'Polonya',
      'Portekiz',
      'Romanya',
      'Ruanda',
      'Rusya',
      'Saint Kitts ve Nevis',
      'Saint Lucia',
      'Saint Vincent ve Grenadinler',
      'Samoa',
      'San Marino',
      'Sao Tome ve Principe',
      'Senegal',
      'Seyşeller',
      'Sırbistan',
      'Sierra Leone',
      'Singapur',
      'Slovakya',
      'Slovenya',
      'Solomon Adaları',
      'Somali',
      'Sri Lanka',
      'Sudan',
      'Surinam',
      'Suriye',
      'Suudi Arabistan',
      'Svaziland (Eswatini)',
      'Şili',
      'Tacikistan',
      'Tanzanya',
      'Tayland',
      'Tayvan',
      'Togo',
      'Tonga',
      'Trinidad ve Tobago',
      'Tunus',
      'Tuvalu',
      'Türkiye',
      'Türkmenistan',
      'Uganda',
      'Ukrayna',
      'Umman',
      'Uruguay',
      'Ürdün',
      'Vanuatu',
      'Vatikan',
      'Venezuela',
      'Vietnam',
      'Yemen',
      'Yeni Zelanda',
      'Yunanistan',
      'Zambiya',
      'Zimbabve',
    ];
  }
  